import ThirdwebProviderV4 from "@/components/Providers/ThirdwebProviderV4";
import "./globals.css";

export const metadata = {
  title: "Istimate Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ThirdwebProviderV4>
          <body>{children}</body>
        </ThirdwebProviderV4>
      </body>
    </html>
  );
}
